// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ASxH8Swgtquj3Muxb0LhqVVUg7fpb5g',
    appId: '1:740959521264:web:d0e538980bfbc00bdaf535',
    messagingSenderId: '740959521264',
    projectId: 'medicare-a9a97',
    authDomain: 'medicare-a9a97.firebaseapp.com',
    storageBucket: 'medicare-a9a97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywZRs7ZZZAa_40H_HM7UOaLVn_0hdCYQ',
    appId: '1:740959521264:android:b513b0f35e7a52c1daf535',
    messagingSenderId: '740959521264',
    projectId: 'medicare-a9a97',
    storageBucket: 'medicare-a9a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ9LJHZ5D3wr9b5eYLdRlqRIn1VMvO3Ps',
    appId: '1:740959521264:ios:4eac2e5121f94ce5daf535',
    messagingSenderId: '740959521264',
    projectId: 'medicare-a9a97',
    storageBucket: 'medicare-a9a97.firebasestorage.app',
    iosBundleId: 'com.example.medicareMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ9LJHZ5D3wr9b5eYLdRlqRIn1VMvO3Ps',
    appId: '1:740959521264:ios:4eac2e5121f94ce5daf535',
    messagingSenderId: '740959521264',
    projectId: 'medicare-a9a97',
    storageBucket: 'medicare-a9a97.firebasestorage.app',
    iosBundleId: 'com.example.medicareMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ASxH8Swgtquj3Muxb0LhqVVUg7fpb5g',
    appId: '1:740959521264:web:09dc29dbd0c825e2daf535',
    messagingSenderId: '740959521264',
    projectId: 'medicare-a9a97',
    authDomain: 'medicare-a9a97.firebaseapp.com',
    storageBucket: 'medicare-a9a97.firebasestorage.app',
  );
}
